version: '3.7'

services:
  fdb-dev:
    container_name: fdb
    image:
      fdb-build-image
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    # restart: always
    volumes:
      - ~/code/foundationdb:/home/renjj/code/foundationdb:Z
      - ./entrypoint.sh:/home/renjj/entrypoint.sh
      - ./fdb.cluster:/etc/foundationdb/fdb.cluster
      - ./.bashrc:/home/renjj/.bashrc
    ports:
      - 4000:4000/tcp
      - "45678:22"
    environment:
      FDB_NETWORKING_MODE: host
      FDB_COORDINATOR_PORT: 4000
      FDB_PORT: 4000
    entrypoint: /home/renjj/entrypoint.sh
